packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  es5-ext: true
  esbuild: true
overrides:
  cookie: 0.7.2
  esbuild: 0.25.12
  brace-expansion: 5.0.8
  "@microsoft/api-extractor": 7.58.12
  fast-uri: 3.1.4
  postcss: 8.5.22
  "read-yaml-file>js-yaml": 3.15.0
  "@changesets/parse>js-yaml": 4.3.0
  "@hey-api/json-schema-ref-parser>js-yaml": 4.3.0
