apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-lab-site
  namespace: media-lab-site
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: media-lab.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: media-lab-site
                port:
                  number: 80
  tls:
    - hosts:
        - media-lab.example.com
      secretName: media-lab-site-tls
