apiVersion: v1
kind: Service
metadata:
  name: media-lab-site
  namespace: media-lab-site
  labels:
    app: media-lab-site
spec:
  selector:
    app: media-lab-site
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
