// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAdminProfileData, GetAdminProfileErrors, GetAdminProfileResponses, GetCardsByRegionByIdData, GetCardsByRegionByIdEpisodesData, GetCardsByRegionByIdEpisodesErrors, GetCardsByRegionByIdEpisodesResponses, GetCardsByRegionByIdErrors, GetCardsByRegionByIdParamsData, GetCardsByRegionByIdParamsErrors, GetCardsByRegionByIdParamsResponses, GetCardsByRegionByIdResponses, GetCardsByRegionListData, GetCardsByRegionListErrors, GetCardsByRegionListResponses, GetCardsByRegionSearchData, GetCardsByRegionSearchErrors, GetCardsByRegionSearchResponses, GetEventsByRegionByIdData, GetEventsByRegionByIdErrors, GetEventsByRegionByIdResponses, GetEventsByRegionByIdRewardsData, GetEventsByRegionByIdRewardsErrors, GetEventsByRegionByIdRewardsResponses, GetEventsByRegionCurrentData, GetEventsByRegionCurrentErrors, GetEventsByRegionCurrentResponses, GetHealthData, GetHealthResponses, GetMasterDataEventsData, GetMasterDataEventsErrors, GetMasterDataEventsResponses, GetMasterDataStatusData, GetMasterDataStatusErrors, GetMasterDataStatusResponses, PostAdminLoginData, PostAdminLoginErrors, PostAdminLoginResponses, PostAdminMasterDataSyncData, PostAdminMasterDataSyncErrors, PostAdminMasterDataSyncForceData, PostAdminMasterDataSyncForceErrors, PostAdminMasterDataSyncForceResponses, PostAdminMasterDataSyncResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login with Keycloak credentials
 */
export const postAdminLogin = <ThrowOnError extends boolean = false>(options: Options<PostAdminLoginData, ThrowOnError>) => (options.client ?? client).post<PostAdminLoginResponses, PostAdminLoginErrors, ThrowOnError>({
    url: '/admin/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Trigger master-data sync
 */
export const postAdminMasterDataSync = <ThrowOnError extends boolean = false>(options?: Options<PostAdminMasterDataSyncData, ThrowOnError>) => (options?.client ?? client).post<PostAdminMasterDataSyncResponses, PostAdminMasterDataSyncErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/master-data/sync',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Trigger force master-data sync
 */
export const postAdminMasterDataSyncForce = <ThrowOnError extends boolean = false>(options?: Options<PostAdminMasterDataSyncForceData, ThrowOnError>) => (options?.client ?? client).post<PostAdminMasterDataSyncForceResponses, PostAdminMasterDataSyncForceErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/master-data/sync/force',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get admin profile
 */
export const getAdminProfile = <ThrowOnError extends boolean = false>(options?: Options<GetAdminProfileData, ThrowOnError>) => (options?.client ?? client).get<GetAdminProfileResponses, GetAdminProfileErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/admin/profile',
    ...options
});

/**
 * List cards by page
 */
export const getCardsByRegionList = <ThrowOnError extends boolean = false>(options: Options<GetCardsByRegionListData, ThrowOnError>) => (options.client ?? client).get<GetCardsByRegionListResponses, GetCardsByRegionListErrors, ThrowOnError>({ url: '/cards/{region}/list', ...options });

/**
 * Search cards by prefix
 */
export const getCardsByRegionSearch = <ThrowOnError extends boolean = false>(options: Options<GetCardsByRegionSearchData, ThrowOnError>) => (options.client ?? client).get<GetCardsByRegionSearchResponses, GetCardsByRegionSearchErrors, ThrowOnError>({ url: '/cards/{region}/search', ...options });

/**
 * Get card basic info by id
 */
export const getCardsByRegionById = <ThrowOnError extends boolean = false>(options: Options<GetCardsByRegionByIdData, ThrowOnError>) => (options.client ?? client).get<GetCardsByRegionByIdResponses, GetCardsByRegionByIdErrors, ThrowOnError>({ url: '/cards/{region}/{id}', ...options });

/**
 * Get card episodes by card id
 */
export const getCardsByRegionByIdEpisodes = <ThrowOnError extends boolean = false>(options: Options<GetCardsByRegionByIdEpisodesData, ThrowOnError>) => (options.client ?? client).get<GetCardsByRegionByIdEpisodesResponses, GetCardsByRegionByIdEpisodesErrors, ThrowOnError>({ url: '/cards/{region}/{id}/episodes', ...options });

/**
 * Get card params by id
 */
export const getCardsByRegionByIdParams = <ThrowOnError extends boolean = false>(options: Options<GetCardsByRegionByIdParamsData, ThrowOnError>) => (options.client ?? client).get<GetCardsByRegionByIdParamsResponses, GetCardsByRegionByIdParamsErrors, ThrowOnError>({ url: '/cards/{region}/{id}/params', ...options });

/**
 * Get current event by region
 */
export const getEventsByRegionCurrent = <ThrowOnError extends boolean = false>(options: Options<GetEventsByRegionCurrentData, ThrowOnError>) => (options.client ?? client).get<GetEventsByRegionCurrentResponses, GetEventsByRegionCurrentErrors, ThrowOnError>({ url: '/events/{region}/current', ...options });

/**
 * Get event basic info by id
 */
export const getEventsByRegionById = <ThrowOnError extends boolean = false>(options: Options<GetEventsByRegionByIdData, ThrowOnError>) => (options.client ?? client).get<GetEventsByRegionByIdResponses, GetEventsByRegionByIdErrors, ThrowOnError>({ url: '/events/{region}/{id}', ...options });

/**
 * Get event rewards by id
 */
export const getEventsByRegionByIdRewards = <ThrowOnError extends boolean = false>(options: Options<GetEventsByRegionByIdRewardsData, ThrowOnError>) => (options.client ?? client).get<GetEventsByRegionByIdRewardsResponses, GetEventsByRegionByIdRewardsErrors, ThrowOnError>({ url: '/events/{region}/{id}/rewards', ...options });

/**
 * Get health status
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Subscribe master-data sync events
 */
export const getMasterDataEvents = <ThrowOnError extends boolean = false>(options?: Options<GetMasterDataEventsData, ThrowOnError>) => (options?.client ?? client).sse.get<GetMasterDataEventsResponses, GetMasterDataEventsErrors, ThrowOnError>({ url: '/master-data/events', ...options });

/**
 * Get master-data sync status
 */
export const getMasterDataStatus = <ThrowOnError extends boolean = false>(options?: Options<GetMasterDataStatusData, ThrowOnError>) => (options?.client ?? client).get<GetMasterDataStatusResponses, GetMasterDataStatusErrors, ThrowOnError>({ url: '/master-data/status', ...options });
