// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type AdminMasterDataSyncRequest = {
    region?: string;
};

export type MasterdataSource = {
    owner?: string;
    path?: string;
    ref?: string;
    region?: string;
    repo?: string;
};

export type MasterdataSyncStatus = {
    error_message?: string;
    file_count?: number;
    last_synced_at?: string;
    region?: string;
    source?: MasterdataSource;
    source_commit?: string;
    status?: string;
    sync_duration_ms?: number;
    updated_at?: string;
};

export type SharedCardListResponse = {
    items?: Array<SharedCardObjectResponse>;
    pagination?: SharedCardPagination;
};

export type SharedCardObjectResponse = {
    archivePublishedAt?: unknown;
    assetbundleName?: unknown;
    attr?: unknown;
    cardParameters?: unknown;
    cardRarity?: SharedCardRarityResponse;
    cardSkillName?: unknown;
    cardSupply?: SharedCardSupplyResponse;
    character?: SharedCharacterResponse;
    flavorText?: unknown;
    gachaPhrase?: unknown;
    id?: unknown;
    initialSpecialTrainingStatus?: unknown;
    prefix?: unknown;
    releaseAt?: unknown;
    seq?: unknown;
    skill?: SharedSkillResponse;
    specialTrainingPower1BonusFixed?: unknown;
    specialTrainingPower2BonusFixed?: unknown;
    specialTrainingPower3BonusFixed?: unknown;
    supportUnit?: unknown;
};

export type SharedCardPagination = {
    has_next?: boolean;
    page?: number;
    page_size?: number;
    total?: number;
    total_pages?: number;
};

export type SharedCardRarityResponse = {
    [key: string]: unknown;
};

export type SharedCardSupplyResponse = {
    [key: string]: unknown;
};

export type SharedCharacterResponse = {
    [key: string]: unknown;
};

export type SharedErrorBody = {
    code?: string;
    message?: string;
};

export type SharedErrorResponse = {
    error?: SharedErrorBody;
};

export type SharedHealthResponse = {
    database?: string;
    status?: string;
};

export type SharedMasterDataAdminStatusResponse = {
    items?: Array<MasterdataSyncStatus>;
    regions?: Array<string>;
    status?: string;
    sync_running?: boolean;
};

export type SharedMasterDataSyncResponse = {
    items?: Array<MasterdataSyncStatus>;
    regions?: Array<string>;
    status?: string;
    sync_running?: boolean;
};

export type SharedProfileAuthDebug = {
    admin_claim?: string;
    claim_values?: Array<string>;
    matched_values?: Array<string>;
};

export type SharedProfileResponse = {
    auth_debug?: SharedProfileAuthDebug;
    user?: SharedProfileUser;
};

export type SharedProfileUser = {
    display_name?: string;
    email?: string;
    id?: string;
    username?: string;
};

export type SharedSkillResponse = {
    [key: string]: unknown;
};

export type GetAdminLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/login';
};

export type GetAdminLoginErrors = {
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
};

export type GetAdminLoginError = GetAdminLoginErrors[keyof GetAdminLoginErrors];

export type GetAdminMasterDataEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/master-data/events';
};

export type GetAdminMasterDataEventsErrors = {
    /**
     * Unauthorized
     */
    401: SharedErrorResponse;
    /**
     * Forbidden
     */
    403: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetAdminMasterDataEventsError = GetAdminMasterDataEventsErrors[keyof GetAdminMasterDataEventsErrors];

export type GetAdminMasterDataEventsResponses = {
    /**
     * SSE stream
     */
    200: string;
};

export type GetAdminMasterDataEventsResponse = GetAdminMasterDataEventsResponses[keyof GetAdminMasterDataEventsResponses];

export type GetAdminMasterDataStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/master-data/status';
};

export type GetAdminMasterDataStatusErrors = {
    /**
     * Unauthorized
     */
    401: SharedErrorResponse;
    /**
     * Forbidden
     */
    403: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
};

export type GetAdminMasterDataStatusError = GetAdminMasterDataStatusErrors[keyof GetAdminMasterDataStatusErrors];

export type GetAdminMasterDataStatusResponses = {
    /**
     * OK
     */
    200: SharedMasterDataAdminStatusResponse;
};

export type GetAdminMasterDataStatusResponse = GetAdminMasterDataStatusResponses[keyof GetAdminMasterDataStatusResponses];

export type PostAdminMasterDataSyncData = {
    /**
     * Optional region-scoped sync payload
     */
    body?: AdminMasterDataSyncRequest;
    path?: never;
    query?: never;
    url: '/admin/master-data/sync';
};

export type PostAdminMasterDataSyncErrors = {
    /**
     * Unauthorized
     */
    401: SharedErrorResponse;
    /**
     * Forbidden
     */
    403: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type PostAdminMasterDataSyncError = PostAdminMasterDataSyncErrors[keyof PostAdminMasterDataSyncErrors];

export type PostAdminMasterDataSyncResponses = {
    /**
     * OK
     */
    200: SharedMasterDataSyncResponse;
};

export type PostAdminMasterDataSyncResponse = PostAdminMasterDataSyncResponses[keyof PostAdminMasterDataSyncResponses];

export type PostAdminMasterDataSyncForceData = {
    /**
     * Optional region-scoped force sync payload
     */
    body?: AdminMasterDataSyncRequest;
    path?: never;
    query?: never;
    url: '/admin/master-data/sync/force';
};

export type PostAdminMasterDataSyncForceErrors = {
    /**
     * Unauthorized
     */
    401: SharedErrorResponse;
    /**
     * Forbidden
     */
    403: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type PostAdminMasterDataSyncForceError = PostAdminMasterDataSyncForceErrors[keyof PostAdminMasterDataSyncForceErrors];

export type PostAdminMasterDataSyncForceResponses = {
    /**
     * OK
     */
    200: SharedMasterDataSyncResponse;
};

export type PostAdminMasterDataSyncForceResponse = PostAdminMasterDataSyncForceResponses[keyof PostAdminMasterDataSyncForceResponses];

export type GetAdminProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/profile';
};

export type GetAdminProfileErrors = {
    /**
     * Unauthorized
     */
    401: SharedErrorResponse;
    /**
     * Forbidden
     */
    403: SharedErrorResponse;
};

export type GetAdminProfileError = GetAdminProfileErrors[keyof GetAdminProfileErrors];

export type GetAdminProfileResponses = {
    /**
     * OK
     */
    200: SharedProfileResponse;
};

export type GetAdminProfileResponse = GetAdminProfileResponses[keyof GetAdminProfileResponses];

export type GetCardsRegionsByIdAvailabilityData = {
    body?: never;
    path: {
        /**
         * Card ID
         */
        id: string;
    };
    query?: never;
    url: '/cards/regions/{id}/availability';
};

export type GetCardsRegionsByIdAvailabilityErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetCardsRegionsByIdAvailabilityError = GetCardsRegionsByIdAvailabilityErrors[keyof GetCardsRegionsByIdAvailabilityErrors];

export type GetCardsRegionsByIdAvailabilityResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCardsRegionsByIdAvailabilityResponse = GetCardsRegionsByIdAvailabilityResponses[keyof GetCardsRegionsByIdAvailabilityResponses];

export type GetCardsByRegionListData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        page_size?: number;
        /**
         * Sort field
         */
        sort_by?: string;
        /**
         * Sort order (asc|desc)
         */
        sort_order?: string;
    };
    url: '/cards/{region}/list';
};

export type GetCardsByRegionListErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetCardsByRegionListError = GetCardsByRegionListErrors[keyof GetCardsByRegionListErrors];

export type GetCardsByRegionListResponses = {
    /**
     * OK
     */
    200: SharedCardListResponse;
};

export type GetCardsByRegionListResponse = GetCardsByRegionListResponses[keyof GetCardsByRegionListResponses];

export type GetCardsByRegionSearchData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query: {
        /**
         * Prefix query
         */
        q: string;
        /**
         * Search field (name|skill), default=name
         */
        field?: string;
        /**
         * Page number
         */
        page?: number;
        /**
         * Max results
         */
        limit?: number;
        /**
         * Sort field
         */
        sort_by?: string;
        /**
         * Sort order (asc|desc)
         */
        sort_order?: string;
    };
    url: '/cards/{region}/search';
};

export type GetCardsByRegionSearchErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetCardsByRegionSearchError = GetCardsByRegionSearchErrors[keyof GetCardsByRegionSearchErrors];

export type GetCardsByRegionSearchResponses = {
    /**
     * OK
     */
    200: SharedCardListResponse;
};

export type GetCardsByRegionSearchResponse = GetCardsByRegionSearchResponses[keyof GetCardsByRegionSearchResponses];

export type GetCardsByRegionByIdData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Card ID
         */
        id: string;
    };
    query?: never;
    url: '/cards/{region}/{id}';
};

export type GetCardsByRegionByIdErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetCardsByRegionByIdError = GetCardsByRegionByIdErrors[keyof GetCardsByRegionByIdErrors];

export type GetCardsByRegionByIdResponses = {
    /**
     * OK
     */
    200: SharedCardObjectResponse;
};

export type GetCardsByRegionByIdResponse = GetCardsByRegionByIdResponses[keyof GetCardsByRegionByIdResponses];

export type GetCardsByRegionByIdEpisodesData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Card ID
         */
        id: string;
    };
    query?: never;
    url: '/cards/{region}/{id}/episodes';
};

export type GetCardsByRegionByIdEpisodesErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetCardsByRegionByIdEpisodesError = GetCardsByRegionByIdEpisodesErrors[keyof GetCardsByRegionByIdEpisodesErrors];

export type GetCardsByRegionByIdEpisodesResponses = {
    /**
     * OK
     */
    200: SharedCardListResponse;
};

export type GetCardsByRegionByIdEpisodesResponse = GetCardsByRegionByIdEpisodesResponses[keyof GetCardsByRegionByIdEpisodesResponses];

export type GetCardsByRegionByIdParamsData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Card ID
         */
        id: string;
    };
    query?: never;
    url: '/cards/{region}/{id}/params';
};

export type GetCardsByRegionByIdParamsErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetCardsByRegionByIdParamsError = GetCardsByRegionByIdParamsErrors[keyof GetCardsByRegionByIdParamsErrors];

export type GetCardsByRegionByIdParamsResponses = {
    /**
     * OK
     */
    200: SharedCardObjectResponse;
};

export type GetCardsByRegionByIdParamsResponse = GetCardsByRegionByIdParamsResponses[keyof GetCardsByRegionByIdParamsResponses];

export type GetEventsRegionsByIdAvailabilityData = {
    body?: never;
    path: {
        /**
         * Event ID
         */
        id: string;
    };
    query?: never;
    url: '/events/regions/{id}/availability';
};

export type GetEventsRegionsByIdAvailabilityErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetEventsRegionsByIdAvailabilityError = GetEventsRegionsByIdAvailabilityErrors[keyof GetEventsRegionsByIdAvailabilityErrors];

export type GetEventsRegionsByIdAvailabilityResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsRegionsByIdAvailabilityResponse = GetEventsRegionsByIdAvailabilityResponses[keyof GetEventsRegionsByIdAvailabilityResponses];

export type GetEventsByRegionCurrentData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: never;
    url: '/events/{region}/current';
};

export type GetEventsByRegionCurrentErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetEventsByRegionCurrentError = GetEventsByRegionCurrentErrors[keyof GetEventsByRegionCurrentErrors];

export type GetEventsByRegionCurrentResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionCurrentResponse = GetEventsByRegionCurrentResponses[keyof GetEventsByRegionCurrentResponses];

export type GetEventsByRegionListData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        page_size?: number;
        /**
         * Sort field
         */
        sort_by?: string;
        /**
         * Sort order (asc|desc)
         */
        sort_order?: string;
    };
    url: '/events/{region}/list';
};

export type GetEventsByRegionListErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetEventsByRegionListError = GetEventsByRegionListErrors[keyof GetEventsByRegionListErrors];

export type GetEventsByRegionListResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionListResponse = GetEventsByRegionListResponses[keyof GetEventsByRegionListResponses];

export type GetEventsByRegionSearchData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query: {
        /**
         * Search query
         */
        q: string;
        /**
         * Search field (name|unit), default=name
         */
        field?: string;
        /**
         * Page number
         */
        page?: number;
        /**
         * Max results
         */
        limit?: number;
        /**
         * Sort field
         */
        sort_by?: string;
        /**
         * Sort order (asc|desc)
         */
        sort_order?: string;
    };
    url: '/events/{region}/search';
};

export type GetEventsByRegionSearchErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetEventsByRegionSearchError = GetEventsByRegionSearchErrors[keyof GetEventsByRegionSearchErrors];

export type GetEventsByRegionSearchResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionSearchResponse = GetEventsByRegionSearchResponses[keyof GetEventsByRegionSearchResponses];

export type GetEventsByRegionByIdData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Event ID
         */
        id: string;
    };
    query?: never;
    url: '/events/{region}/{id}';
};

export type GetEventsByRegionByIdErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetEventsByRegionByIdError = GetEventsByRegionByIdErrors[keyof GetEventsByRegionByIdErrors];

export type GetEventsByRegionByIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionByIdResponse = GetEventsByRegionByIdResponses[keyof GetEventsByRegionByIdResponses];

export type GetEventsByRegionByIdBonusesData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Event ID
         */
        id: string;
    };
    query?: never;
    url: '/events/{region}/{id}/bonuses';
};

export type GetEventsByRegionByIdBonusesErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetEventsByRegionByIdBonusesError = GetEventsByRegionByIdBonusesErrors[keyof GetEventsByRegionByIdBonusesErrors];

export type GetEventsByRegionByIdBonusesResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionByIdBonusesResponse = GetEventsByRegionByIdBonusesResponses[keyof GetEventsByRegionByIdBonusesResponses];

export type GetEventsByRegionByIdBreakTimesData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Event ID
         */
        id: string;
    };
    query?: never;
    url: '/events/{region}/{id}/break-times';
};

export type GetEventsByRegionByIdBreakTimesErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetEventsByRegionByIdBreakTimesError = GetEventsByRegionByIdBreakTimesErrors[keyof GetEventsByRegionByIdBreakTimesErrors];

export type GetEventsByRegionByIdBreakTimesResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionByIdBreakTimesResponse = GetEventsByRegionByIdBreakTimesResponses[keyof GetEventsByRegionByIdBreakTimesResponses];

export type GetEventsByRegionByIdCardsData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Event ID
         */
        id: string;
    };
    query?: never;
    url: '/events/{region}/{id}/cards';
};

export type GetEventsByRegionByIdCardsErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetEventsByRegionByIdCardsError = GetEventsByRegionByIdCardsErrors[keyof GetEventsByRegionByIdCardsErrors];

export type GetEventsByRegionByIdCardsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionByIdCardsResponse = GetEventsByRegionByIdCardsResponses[keyof GetEventsByRegionByIdCardsResponses];

export type GetEventsByRegionByIdMusicsData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Event ID
         */
        id: string;
    };
    query?: never;
    url: '/events/{region}/{id}/musics';
};

export type GetEventsByRegionByIdMusicsErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetEventsByRegionByIdMusicsError = GetEventsByRegionByIdMusicsErrors[keyof GetEventsByRegionByIdMusicsErrors];

export type GetEventsByRegionByIdMusicsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionByIdMusicsResponse = GetEventsByRegionByIdMusicsResponses[keyof GetEventsByRegionByIdMusicsResponses];

export type GetEventsByRegionByIdRewardsData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Event ID
         */
        id: string;
    };
    query?: never;
    url: '/events/{region}/{id}/rewards';
};

export type GetEventsByRegionByIdRewardsErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetEventsByRegionByIdRewardsError = GetEventsByRegionByIdRewardsErrors[keyof GetEventsByRegionByIdRewardsErrors];

export type GetEventsByRegionByIdRewardsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionByIdRewardsResponse = GetEventsByRegionByIdRewardsResponses[keyof GetEventsByRegionByIdRewardsResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: SharedHealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostInternalGithubWebhooksMasterDataData = {
    /**
     * GitHub webhook payload
     */
    body: {
        [key: string]: unknown;
    };
    headers: {
        /**
         * GitHub event type
         */
        'X-GitHub-Event': string;
        /**
         * GitHub HMAC SHA-256 signature
         */
        'X-Hub-Signature-256'?: string;
    };
    path?: never;
    query?: never;
    url: '/internal/github/webhooks/master-data';
};

export type PostInternalGithubWebhooksMasterDataErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Unauthorized
     */
    401: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type PostInternalGithubWebhooksMasterDataError = PostInternalGithubWebhooksMasterDataErrors[keyof PostInternalGithubWebhooksMasterDataErrors];

export type PostInternalGithubWebhooksMasterDataResponses = {
    /**
     * Accepted
     */
    202: {
        [key: string]: unknown;
    };
};

export type PostInternalGithubWebhooksMasterDataResponse = PostInternalGithubWebhooksMasterDataResponses[keyof PostInternalGithubWebhooksMasterDataResponses];

export type GetMusicsRegionsByIdAvailabilityData = {
    body?: never;
    path: {
        /**
         * Music ID
         */
        id: string;
    };
    query?: never;
    url: '/musics/regions/{id}/availability';
};

export type GetMusicsRegionsByIdAvailabilityErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetMusicsRegionsByIdAvailabilityError = GetMusicsRegionsByIdAvailabilityErrors[keyof GetMusicsRegionsByIdAvailabilityErrors];

export type GetMusicsRegionsByIdAvailabilityResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetMusicsRegionsByIdAvailabilityResponse = GetMusicsRegionsByIdAvailabilityResponses[keyof GetMusicsRegionsByIdAvailabilityResponses];

export type GetMusicsByRegionListData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        page_size?: number;
        /**
         * Sort field
         */
        sort_by?: string;
        /**
         * Sort order (asc|desc)
         */
        sort_order?: string;
    };
    url: '/musics/{region}/list';
};

export type GetMusicsByRegionListErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetMusicsByRegionListError = GetMusicsByRegionListErrors[keyof GetMusicsByRegionListErrors];

export type GetMusicsByRegionListResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetMusicsByRegionListResponse = GetMusicsByRegionListResponses[keyof GetMusicsByRegionListResponses];

export type GetMusicsByRegionSearchData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: {
        /**
         * Keyword for title field
         */
        title?: string;
        /**
         * Keyword for lyricist field
         */
        lyricist?: string;
        /**
         * Keyword for composer field
         */
        composer?: string;
        /**
         * Keyword for arranger field
         */
        arranger?: string;
        /**
         * Page number
         */
        page?: number;
        /**
         * Max results
         */
        limit?: number;
        /**
         * Sort field
         */
        sort_by?: string;
        /**
         * Sort order (asc|desc)
         */
        sort_order?: string;
    };
    url: '/musics/{region}/search';
};

export type GetMusicsByRegionSearchErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetMusicsByRegionSearchError = GetMusicsByRegionSearchErrors[keyof GetMusicsByRegionSearchErrors];

export type GetMusicsByRegionSearchResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetMusicsByRegionSearchResponse = GetMusicsByRegionSearchResponses[keyof GetMusicsByRegionSearchResponses];

export type GetMusicsByRegionByIdData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Music ID
         */
        id: string;
    };
    query?: never;
    url: '/musics/{region}/{id}';
};

export type GetMusicsByRegionByIdErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetMusicsByRegionByIdError = GetMusicsByRegionByIdErrors[keyof GetMusicsByRegionByIdErrors];

export type GetMusicsByRegionByIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetMusicsByRegionByIdResponse = GetMusicsByRegionByIdResponses[keyof GetMusicsByRegionByIdResponses];

export type GetVersionsByRegionData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: never;
    url: '/versions/{region}';
};

export type GetVersionsByRegionErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetVersionsByRegionError = GetVersionsByRegionErrors[keyof GetVersionsByRegionErrors];

export type GetVersionsByRegionResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVersionsByRegionResponse = GetVersionsByRegionResponses[keyof GetVersionsByRegionResponses];

export type GetVirtualLivesRegionsByIdAvailabilityData = {
    body?: never;
    path: {
        /**
         * Virtual Live ID
         */
        id: string;
    };
    query?: never;
    url: '/virtualLives/regions/{id}/availability';
};

export type GetVirtualLivesRegionsByIdAvailabilityErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetVirtualLivesRegionsByIdAvailabilityError = GetVirtualLivesRegionsByIdAvailabilityErrors[keyof GetVirtualLivesRegionsByIdAvailabilityErrors];

export type GetVirtualLivesRegionsByIdAvailabilityResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVirtualLivesRegionsByIdAvailabilityResponse = GetVirtualLivesRegionsByIdAvailabilityResponses[keyof GetVirtualLivesRegionsByIdAvailabilityResponses];

export type GetVirtualLivesByRegionListData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        page_size?: number;
        /**
         * Sort field
         */
        sort_by?: string;
        /**
         * Sort order (asc|desc)
         */
        sort_order?: string;
    };
    url: '/virtualLives/{region}/list';
};

export type GetVirtualLivesByRegionListErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetVirtualLivesByRegionListError = GetVirtualLivesByRegionListErrors[keyof GetVirtualLivesByRegionListErrors];

export type GetVirtualLivesByRegionListResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVirtualLivesByRegionListResponse = GetVirtualLivesByRegionListResponses[keyof GetVirtualLivesByRegionListResponses];

export type GetVirtualLivesByRegionSearchData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query: {
        /**
         * Search query
         */
        q: string;
        /**
         * Search field (name|type|assetbundle), default=name
         */
        field?: string;
        /**
         * Page number
         */
        page?: number;
        /**
         * Max results
         */
        limit?: number;
        /**
         * Sort field
         */
        sort_by?: string;
        /**
         * Sort order (asc|desc)
         */
        sort_order?: string;
    };
    url: '/virtualLives/{region}/search';
};

export type GetVirtualLivesByRegionSearchErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetVirtualLivesByRegionSearchError = GetVirtualLivesByRegionSearchErrors[keyof GetVirtualLivesByRegionSearchErrors];

export type GetVirtualLivesByRegionSearchResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVirtualLivesByRegionSearchResponse = GetVirtualLivesByRegionSearchResponses[keyof GetVirtualLivesByRegionSearchResponses];

export type GetVirtualLivesByRegionByIdData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Virtual Live ID
         */
        id: string;
    };
    query?: never;
    url: '/virtualLives/{region}/{id}';
};

export type GetVirtualLivesByRegionByIdErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetVirtualLivesByRegionByIdError = GetVirtualLivesByRegionByIdErrors[keyof GetVirtualLivesByRegionByIdErrors];

export type GetVirtualLivesByRegionByIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVirtualLivesByRegionByIdResponse = GetVirtualLivesByRegionByIdResponses[keyof GetVirtualLivesByRegionByIdResponses];

export type GetVirtualLivesByRegionByIdItemsData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Virtual Live ID
         */
        id: string;
    };
    query?: never;
    url: '/virtualLives/{region}/{id}/items';
};

export type GetVirtualLivesByRegionByIdItemsErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetVirtualLivesByRegionByIdItemsError = GetVirtualLivesByRegionByIdItemsErrors[keyof GetVirtualLivesByRegionByIdItemsErrors];

export type GetVirtualLivesByRegionByIdItemsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVirtualLivesByRegionByIdItemsResponse = GetVirtualLivesByRegionByIdItemsResponses[keyof GetVirtualLivesByRegionByIdItemsResponses];

export type GetVirtualLivesByRegionByIdSchedulesData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Virtual Live ID
         */
        id: string;
    };
    query?: never;
    url: '/virtualLives/{region}/{id}/schedules';
};

export type GetVirtualLivesByRegionByIdSchedulesErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetVirtualLivesByRegionByIdSchedulesError = GetVirtualLivesByRegionByIdSchedulesErrors[keyof GetVirtualLivesByRegionByIdSchedulesErrors];

export type GetVirtualLivesByRegionByIdSchedulesResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVirtualLivesByRegionByIdSchedulesResponse = GetVirtualLivesByRegionByIdSchedulesResponses[keyof GetVirtualLivesByRegionByIdSchedulesResponses];

export type GetVirtualLivesByRegionByIdSetlistsData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Virtual Live ID
         */
        id: string;
    };
    query?: never;
    url: '/virtualLives/{region}/{id}/setlists';
};

export type GetVirtualLivesByRegionByIdSetlistsErrors = {
    /**
     * Bad Request
     */
    400: SharedErrorResponse;
    /**
     * Not Found
     */
    404: SharedErrorResponse;
    /**
     * Internal Server Error
     */
    500: SharedErrorResponse;
    /**
     * Service Unavailable
     */
    503: SharedErrorResponse;
};

export type GetVirtualLivesByRegionByIdSetlistsError = GetVirtualLivesByRegionByIdSetlistsErrors[keyof GetVirtualLivesByRegionByIdSetlistsErrors];

export type GetVirtualLivesByRegionByIdSetlistsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetVirtualLivesByRegionByIdSetlistsResponse = GetVirtualLivesByRegionByIdSetlistsResponses[keyof GetVirtualLivesByRegionByIdSetlistsResponses];
