// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type HandlerCardListResponse = {
    items?: Array<HandlerCardObjectResponse>;
    pagination?: HandlerCardPagination;
};

export type HandlerCardObjectResponse = {
    archivePublishedAt?: unknown;
    assetbundleName?: unknown;
    attr?: unknown;
    cardParameters?: unknown;
    cardRarity?: HandlerCardRarityResponse;
    cardSkillName?: unknown;
    cardSupply?: HandlerCardSupplyResponse;
    character?: HandlerCharacterResponse;
    flavorText?: unknown;
    gachaPhrase?: unknown;
    id?: unknown;
    initialSpecialTrainingStatus?: unknown;
    prefix?: unknown;
    releaseAt?: unknown;
    seq?: unknown;
    skill?: HandlerSkillResponse;
    specialTrainingPower1BonusFixed?: unknown;
    specialTrainingPower2BonusFixed?: unknown;
    specialTrainingPower3BonusFixed?: unknown;
    supportUnit?: unknown;
};

export type HandlerCardPagination = {
    has_next?: boolean;
    page?: number;
    page_size?: number;
    total?: number;
    total_pages?: number;
};

export type HandlerCardRarityResponse = {
    [key: string]: unknown;
};

export type HandlerCardSupplyResponse = {
    [key: string]: unknown;
};

export type HandlerCharacterResponse = {
    [key: string]: unknown;
};

export type HandlerErrorBody = {
    code?: string;
    message?: string;
};

export type HandlerErrorResponse = {
    error?: HandlerErrorBody;
};

export type HandlerHealthResponse = {
    database?: string;
    status?: string;
};

export type HandlerMasterDataAdminStatusResponse = {
    items?: Array<MasterdataSyncStatus>;
    regions?: Array<string>;
    status?: string;
    sync_running?: boolean;
};

export type HandlerMasterDataSyncResponse = {
    items?: Array<MasterdataSyncStatus>;
    regions?: Array<string>;
    status?: string;
    sync_running?: boolean;
};

export type HandlerProfileAuthDebug = {
    admin_claim?: string;
    claim_values?: Array<string>;
    matched_values?: Array<string>;
};

export type HandlerProfileResponse = {
    auth_debug?: HandlerProfileAuthDebug;
    user?: HandlerProfileUser;
};

export type HandlerProfileUser = {
    display_name?: string;
    email?: string;
    id?: string;
    username?: string;
};

export type HandlerSkillResponse = {
    [key: string]: unknown;
};

export type HandlerMasterDataSyncRequest = {
    region?: string;
};

export type MasterdataSource = {
    owner?: string;
    path?: string;
    ref?: string;
    region?: string;
    repo?: string;
};

export type MasterdataSyncStatus = {
    error_message?: string;
    file_count?: number;
    last_synced_at?: string;
    region?: string;
    source?: MasterdataSource;
    source_commit?: string;
    status?: string;
    sync_duration_ms?: number;
    updated_at?: string;
};

export type GetAdminLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/login';
};

export type GetAdminLoginErrors = {
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
};

export type GetAdminLoginError = GetAdminLoginErrors[keyof GetAdminLoginErrors];

export type GetAdminMasterDataEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/master-data/events';
};

export type GetAdminMasterDataEventsErrors = {
    /**
     * Unauthorized
     */
    401: HandlerErrorResponse;
    /**
     * Forbidden
     */
    403: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetAdminMasterDataEventsError = GetAdminMasterDataEventsErrors[keyof GetAdminMasterDataEventsErrors];

export type GetAdminMasterDataEventsResponses = {
    /**
     * SSE stream
     */
    200: string;
};

export type GetAdminMasterDataEventsResponse = GetAdminMasterDataEventsResponses[keyof GetAdminMasterDataEventsResponses];

export type GetAdminMasterDataStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/master-data/status';
};

export type GetAdminMasterDataStatusErrors = {
    /**
     * Unauthorized
     */
    401: HandlerErrorResponse;
    /**
     * Forbidden
     */
    403: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
};

export type GetAdminMasterDataStatusError = GetAdminMasterDataStatusErrors[keyof GetAdminMasterDataStatusErrors];

export type GetAdminMasterDataStatusResponses = {
    /**
     * OK
     */
    200: HandlerMasterDataAdminStatusResponse;
};

export type GetAdminMasterDataStatusResponse = GetAdminMasterDataStatusResponses[keyof GetAdminMasterDataStatusResponses];

export type PostAdminMasterDataSyncData = {
    /**
     * Optional region-scoped sync payload
     */
    body?: HandlerMasterDataSyncRequest;
    path?: never;
    query?: never;
    url: '/admin/master-data/sync';
};

export type PostAdminMasterDataSyncErrors = {
    /**
     * Unauthorized
     */
    401: HandlerErrorResponse;
    /**
     * Forbidden
     */
    403: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type PostAdminMasterDataSyncError = PostAdminMasterDataSyncErrors[keyof PostAdminMasterDataSyncErrors];

export type PostAdminMasterDataSyncResponses = {
    /**
     * OK
     */
    200: HandlerMasterDataSyncResponse;
};

export type PostAdminMasterDataSyncResponse = PostAdminMasterDataSyncResponses[keyof PostAdminMasterDataSyncResponses];

export type PostAdminMasterDataSyncForceData = {
    /**
     * Optional region-scoped force sync payload
     */
    body?: HandlerMasterDataSyncRequest;
    path?: never;
    query?: never;
    url: '/admin/master-data/sync/force';
};

export type PostAdminMasterDataSyncForceErrors = {
    /**
     * Unauthorized
     */
    401: HandlerErrorResponse;
    /**
     * Forbidden
     */
    403: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type PostAdminMasterDataSyncForceError = PostAdminMasterDataSyncForceErrors[keyof PostAdminMasterDataSyncForceErrors];

export type PostAdminMasterDataSyncForceResponses = {
    /**
     * OK
     */
    200: HandlerMasterDataSyncResponse;
};

export type PostAdminMasterDataSyncForceResponse = PostAdminMasterDataSyncForceResponses[keyof PostAdminMasterDataSyncForceResponses];

export type GetAdminProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/profile';
};

export type GetAdminProfileErrors = {
    /**
     * Unauthorized
     */
    401: HandlerErrorResponse;
    /**
     * Forbidden
     */
    403: HandlerErrorResponse;
};

export type GetAdminProfileError = GetAdminProfileErrors[keyof GetAdminProfileErrors];

export type GetAdminProfileResponses = {
    /**
     * OK
     */
    200: HandlerProfileResponse;
};

export type GetAdminProfileResponse = GetAdminProfileResponses[keyof GetAdminProfileResponses];

export type GetCardsRegionsByIdAvailabilityData = {
    body?: never;
    path: {
        /**
         * Card ID
         */
        id: string;
    };
    query?: never;
    url: '/cards/regions/{id}/availability';
};

export type GetCardsRegionsByIdAvailabilityErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetCardsRegionsByIdAvailabilityError = GetCardsRegionsByIdAvailabilityErrors[keyof GetCardsRegionsByIdAvailabilityErrors];

export type GetCardsRegionsByIdAvailabilityResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCardsRegionsByIdAvailabilityResponse = GetCardsRegionsByIdAvailabilityResponses[keyof GetCardsRegionsByIdAvailabilityResponses];

export type GetCardsByRegionListData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        page_size?: number;
    };
    url: '/cards/{region}/list';
};

export type GetCardsByRegionListErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetCardsByRegionListError = GetCardsByRegionListErrors[keyof GetCardsByRegionListErrors];

export type GetCardsByRegionListResponses = {
    /**
     * OK
     */
    200: HandlerCardListResponse;
};

export type GetCardsByRegionListResponse = GetCardsByRegionListResponses[keyof GetCardsByRegionListResponses];

export type GetCardsByRegionSearchData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query: {
        /**
         * Prefix query
         */
        q: string;
        /**
         * Search field (name|skill), default=name
         */
        field?: string;
        /**
         * Page number
         */
        page?: number;
        /**
         * Max results
         */
        limit?: number;
    };
    url: '/cards/{region}/search';
};

export type GetCardsByRegionSearchErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetCardsByRegionSearchError = GetCardsByRegionSearchErrors[keyof GetCardsByRegionSearchErrors];

export type GetCardsByRegionSearchResponses = {
    /**
     * OK
     */
    200: HandlerCardListResponse;
};

export type GetCardsByRegionSearchResponse = GetCardsByRegionSearchResponses[keyof GetCardsByRegionSearchResponses];

export type GetCardsByRegionByIdData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Card ID
         */
        id: string;
    };
    query?: never;
    url: '/cards/{region}/{id}';
};

export type GetCardsByRegionByIdErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Not Found
     */
    404: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetCardsByRegionByIdError = GetCardsByRegionByIdErrors[keyof GetCardsByRegionByIdErrors];

export type GetCardsByRegionByIdResponses = {
    /**
     * OK
     */
    200: HandlerCardObjectResponse;
};

export type GetCardsByRegionByIdResponse = GetCardsByRegionByIdResponses[keyof GetCardsByRegionByIdResponses];

export type GetCardsByRegionByIdEpisodesData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Card ID
         */
        id: string;
    };
    query?: never;
    url: '/cards/{region}/{id}/episodes';
};

export type GetCardsByRegionByIdEpisodesErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Not Found
     */
    404: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetCardsByRegionByIdEpisodesError = GetCardsByRegionByIdEpisodesErrors[keyof GetCardsByRegionByIdEpisodesErrors];

export type GetCardsByRegionByIdEpisodesResponses = {
    /**
     * OK
     */
    200: HandlerCardListResponse;
};

export type GetCardsByRegionByIdEpisodesResponse = GetCardsByRegionByIdEpisodesResponses[keyof GetCardsByRegionByIdEpisodesResponses];

export type GetCardsByRegionByIdParamsData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Card ID
         */
        id: string;
    };
    query?: never;
    url: '/cards/{region}/{id}/params';
};

export type GetCardsByRegionByIdParamsErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Not Found
     */
    404: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetCardsByRegionByIdParamsError = GetCardsByRegionByIdParamsErrors[keyof GetCardsByRegionByIdParamsErrors];

export type GetCardsByRegionByIdParamsResponses = {
    /**
     * OK
     */
    200: HandlerCardObjectResponse;
};

export type GetCardsByRegionByIdParamsResponse = GetCardsByRegionByIdParamsResponses[keyof GetCardsByRegionByIdParamsResponses];

export type GetEventsRegionsByIdAvailabilityData = {
    body?: never;
    path: {
        /**
         * Event ID
         */
        id: string;
    };
    query?: never;
    url: '/events/regions/{id}/availability';
};

export type GetEventsRegionsByIdAvailabilityErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetEventsRegionsByIdAvailabilityError = GetEventsRegionsByIdAvailabilityErrors[keyof GetEventsRegionsByIdAvailabilityErrors];

export type GetEventsRegionsByIdAvailabilityResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsRegionsByIdAvailabilityResponse = GetEventsRegionsByIdAvailabilityResponses[keyof GetEventsRegionsByIdAvailabilityResponses];

export type GetEventsByRegionCurrentData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: never;
    url: '/events/{region}/current';
};

export type GetEventsByRegionCurrentErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Not Found
     */
    404: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetEventsByRegionCurrentError = GetEventsByRegionCurrentErrors[keyof GetEventsByRegionCurrentErrors];

export type GetEventsByRegionCurrentResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionCurrentResponse = GetEventsByRegionCurrentResponses[keyof GetEventsByRegionCurrentResponses];

export type GetEventsByRegionByIdData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Event ID
         */
        id: string;
    };
    query?: never;
    url: '/events/{region}/{id}';
};

export type GetEventsByRegionByIdErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Not Found
     */
    404: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetEventsByRegionByIdError = GetEventsByRegionByIdErrors[keyof GetEventsByRegionByIdErrors];

export type GetEventsByRegionByIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionByIdResponse = GetEventsByRegionByIdResponses[keyof GetEventsByRegionByIdResponses];

export type GetEventsByRegionByIdRewardsData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Event ID
         */
        id: string;
    };
    query?: never;
    url: '/events/{region}/{id}/rewards';
};

export type GetEventsByRegionByIdRewardsErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Not Found
     */
    404: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetEventsByRegionByIdRewardsError = GetEventsByRegionByIdRewardsErrors[keyof GetEventsByRegionByIdRewardsErrors];

export type GetEventsByRegionByIdRewardsResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetEventsByRegionByIdRewardsResponse = GetEventsByRegionByIdRewardsResponses[keyof GetEventsByRegionByIdRewardsResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: HandlerHealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetMusicsRegionsByIdAvailabilityData = {
    body?: never;
    path: {
        /**
         * Music ID
         */
        id: string;
    };
    query?: never;
    url: '/musics/regions/{id}/availability';
};

export type GetMusicsRegionsByIdAvailabilityErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetMusicsRegionsByIdAvailabilityError = GetMusicsRegionsByIdAvailabilityErrors[keyof GetMusicsRegionsByIdAvailabilityErrors];

export type GetMusicsRegionsByIdAvailabilityResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetMusicsRegionsByIdAvailabilityResponse = GetMusicsRegionsByIdAvailabilityResponses[keyof GetMusicsRegionsByIdAvailabilityResponses];

export type GetMusicsByRegionListData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Page size
         */
        page_size?: number;
    };
    url: '/musics/{region}/list';
};

export type GetMusicsByRegionListErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetMusicsByRegionListError = GetMusicsByRegionListErrors[keyof GetMusicsByRegionListErrors];

export type GetMusicsByRegionListResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetMusicsByRegionListResponse = GetMusicsByRegionListResponses[keyof GetMusicsByRegionListResponses];

export type GetMusicsByRegionSearchData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
    };
    query?: {
        /**
         * Keyword for title field
         */
        title?: string;
        /**
         * Keyword for lyricist field
         */
        lyricist?: string;
        /**
         * Keyword for composer field
         */
        composer?: string;
        /**
         * Keyword for arranger field
         */
        arranger?: string;
        /**
         * Page number
         */
        page?: number;
        /**
         * Max results
         */
        limit?: number;
    };
    url: '/musics/{region}/search';
};

export type GetMusicsByRegionSearchErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetMusicsByRegionSearchError = GetMusicsByRegionSearchErrors[keyof GetMusicsByRegionSearchErrors];

export type GetMusicsByRegionSearchResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetMusicsByRegionSearchResponse = GetMusicsByRegionSearchResponses[keyof GetMusicsByRegionSearchResponses];

export type GetMusicsByRegionByIdData = {
    body?: never;
    path: {
        /**
         * Region
         */
        region: string;
        /**
         * Music ID
         */
        id: string;
    };
    query?: never;
    url: '/musics/{region}/{id}';
};

export type GetMusicsByRegionByIdErrors = {
    /**
     * Bad Request
     */
    400: HandlerErrorResponse;
    /**
     * Not Found
     */
    404: HandlerErrorResponse;
    /**
     * Internal Server Error
     */
    500: HandlerErrorResponse;
    /**
     * Service Unavailable
     */
    503: HandlerErrorResponse;
};

export type GetMusicsByRegionByIdError = GetMusicsByRegionByIdErrors[keyof GetMusicsByRegionByIdErrors];

export type GetMusicsByRegionByIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetMusicsByRegionByIdResponse = GetMusicsByRegionByIdResponses[keyof GetMusicsByRegionByIdResponses];
