apiVersion: v1
kind: Service
metadata:
  name: content-site
  namespace: content-site
  labels:
    app: content-site
spec:
  selector:
    app: content-site
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
