// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiInfoData, GetApiInfoResponses, GetEventChapterRankingGrpahByEventIdAndCharaIdData, GetEventChapterRankingGrpahByEventIdAndCharaIdResponses, GetEventChapterRankingLiveData, GetEventChapterRankingLiveResponses, GetEventChapterRankingsByEventIdAndCharaIdData, GetEventChapterRankingsByEventIdAndCharaIdResponses, GetEventChapterRankingTimePointsData, GetEventChapterRankingTimePointsResponses, GetEventLatestChapterRankingLiveData, GetEventLatestChapterRankingLiveResponses, GetEventRankingGrpahByEventIdData, GetEventRankingGrpahByEventIdResponses, GetEventRankingLiveData, GetEventRankingLiveResponses, GetEventRankingsByEventIdData, GetEventRankingsByEventIdResponses, GetEventRankingTimePointsData, GetEventRankingTimePointsResponses, GetOpenApiSpecData, GetOpenApiSpecResponses, HealthcheckData, HealthcheckResponses, PostEventChapterRankingData, PostEventChapterRankingErrors, PostEventChapterRankingResponses, PostEventRankingData, PostEventRankingErrors, PostEventRankingResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get event chapter rankings of an event.
 */
export const getEventChapterRankingsByEventIdAndCharaId = <ThrowOnError extends boolean = false>(options: Options<GetEventChapterRankingsByEventIdAndCharaIdData, ThrowOnError>): RequestResult<GetEventChapterRankingsByEventIdAndCharaIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetEventChapterRankingsByEventIdAndCharaIdResponses, unknown, ThrowOnError>({
    querySerializer: { parameters: { sort: { object: { style: 'form' } } } },
    url: '/event/{id}/chapter_rankings',
    ...options
});

/**
 * Record event rankings of an event.
 */
export const postEventChapterRanking = <ThrowOnError extends boolean = false>(options: Options<PostEventChapterRankingData, ThrowOnError>): RequestResult<PostEventChapterRankingResponses, PostEventChapterRankingErrors, ThrowOnError> => (options.client ?? client).post<PostEventChapterRankingResponses, PostEventChapterRankingErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/event/{id}/chapter_rankings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get event chapter rankings of an event for drawing graph.
 */
export const getEventChapterRankingGrpahByEventIdAndCharaId = <ThrowOnError extends boolean = false>(options: Options<GetEventChapterRankingGrpahByEventIdAndCharaIdData, ThrowOnError>): RequestResult<GetEventChapterRankingGrpahByEventIdAndCharaIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetEventChapterRankingGrpahByEventIdAndCharaIdResponses, unknown, ThrowOnError>({ url: '/event/{id}/chapter_rankings/graph', ...options });

/**
 * Get recorded time points of an world bloom event chapter for time travelling.
 */
export const getEventChapterRankingTimePoints = <ThrowOnError extends boolean = false>(options: Options<GetEventChapterRankingTimePointsData, ThrowOnError>): RequestResult<GetEventChapterRankingTimePointsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetEventChapterRankingTimePointsResponses, unknown, ThrowOnError>({ url: '/event/{id}/chapter_rankings/time', ...options });

/**
 * Get current event rankings.
 */
export const getEventRankingLive = <ThrowOnError extends boolean = false>(options?: Options<GetEventRankingLiveData, ThrowOnError>): RequestResult<GetEventRankingLiveResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetEventRankingLiveResponses, unknown, ThrowOnError>({ url: '/event/live', ...options });

/**
 * Get current world link event rankings of given chapter (character).
 */
export const getEventChapterRankingLive = <ThrowOnError extends boolean = false>(options: Options<GetEventChapterRankingLiveData, ThrowOnError>): RequestResult<GetEventChapterRankingLiveResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetEventChapterRankingLiveResponses, unknown, ThrowOnError>({ url: '/event/live_chapter_rankings', ...options });

/**
 * Get latest world link event rankings of current chapter (character).
 */
export const getEventLatestChapterRankingLive = <ThrowOnError extends boolean = false>(options?: Options<GetEventLatestChapterRankingLiveData, ThrowOnError>): RequestResult<GetEventLatestChapterRankingLiveResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetEventLatestChapterRankingLiveResponses, unknown, ThrowOnError>({ url: '/event/live_latest_chapter', ...options });

/**
 * Get event rankings of an event.
 */
export const getEventRankingsByEventId = <ThrowOnError extends boolean = false>(options: Options<GetEventRankingsByEventIdData, ThrowOnError>): RequestResult<GetEventRankingsByEventIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetEventRankingsByEventIdResponses, unknown, ThrowOnError>({
    querySerializer: { parameters: { sort: { object: { style: 'form' } } } },
    url: '/event/{id}/rankings',
    ...options
});

/**
 * Record event rankings of an event.
 */
export const postEventRanking = <ThrowOnError extends boolean = false>(options: Options<PostEventRankingData, ThrowOnError>): RequestResult<PostEventRankingResponses, PostEventRankingErrors, ThrowOnError> => (options.client ?? client).post<PostEventRankingResponses, PostEventRankingErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/event/{id}/rankings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get event rankings of an event for drawing graph.
 */
export const getEventRankingGrpahByEventId = <ThrowOnError extends boolean = false>(options: Options<GetEventRankingGrpahByEventIdData, ThrowOnError>): RequestResult<GetEventRankingGrpahByEventIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetEventRankingGrpahByEventIdResponses, unknown, ThrowOnError>({ url: '/event/{id}/rankings/graph', ...options });

/**
 * Get recorded time points of an event for time travelling.
 */
export const getEventRankingTimePoints = <ThrowOnError extends boolean = false>(options: Options<GetEventRankingTimePointsData, ThrowOnError>): RequestResult<GetEventRankingTimePointsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetEventRankingTimePointsResponses, unknown, ThrowOnError>({ url: '/event/{id}/rankings/time', ...options });

/**
 * Get a general API information.
 */
export const getApiInfo = <ThrowOnError extends boolean = false>(options?: Options<GetApiInfoData, ThrowOnError>): RequestResult<GetApiInfoResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiInfoResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Get Open API Specification.
 */
export const getOpenApiSpec = <ThrowOnError extends boolean = false>(options?: Options<GetOpenApiSpecData, ThrowOnError>): RequestResult<GetOpenApiSpecResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetOpenApiSpecResponses, unknown, ThrowOnError>({ url: '/spec', ...options });

/**
 * Provide a detailed information about the service health.
 */
export const healthcheck = <ThrowOnError extends boolean = false>(options?: Options<HealthcheckData, ThrowOnError>): RequestResult<HealthcheckResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthcheckResponses, unknown, ThrowOnError>({ url: '/status', ...options });
