// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type ResponseStatus = 'success' | 'fail' | 'error';

export type ResponseCodeForFailure = 'UNKNOWN_ENDPOINT' | 'INVALID_REQUEST';

export type ResponseCodeForError = 'UNKNOWN_ERROR' | 'INTERNAL_ERROR';

export type SuccessResponse = {
    status: ResponseStatus;
    data: {
        [key: string]: unknown;
    } | null;
    message: string;
};

export type FailureResponse = {
    status: ResponseStatus;
    code: ResponseCodeForFailure;
    data: Array<{
        param?: string;
        message?: string;
    }> | null;
    message: string;
};

export type ErrorResponse = {
    status: ResponseStatus;
    code: ResponseCodeForFailure;
    data: Array<{
        param?: string;
        message?: string;
    }> | null;
    message: string;
};

export type Password = string;

export type EventTrackerData = {
    time?: number;
    first100?: Array<EventTrackerRanking>;
    border?: Array<EventTrackerRanking>;
};

export type EventChapterTrackerData = {
    time?: number;
    first100?: Array<EventChapterTrackerRanking>;
    border?: Array<EventChapterTrackerRanking>;
};

export type EventTrackerRanking = {
    id?: number;
    eventId?: number;
    timestamp?: string;
    score?: number;
    rank?: number;
    userId?: string;
    userName?: string;
    userCard?: {
        cardId?: number;
        level?: number;
        masterRank?: number;
        specialTrainingStatus?: string;
        defaultImage?: string;
    };
    userProfile?: {
        userId?: number;
        word?: string;
        honorId1?: number;
        honorLevel1?: number;
        honorId2?: number;
        honorLevel2?: number;
        honorId3?: number;
        honorLevel3?: number;
        twitterId?: string;
        profileImageType?: string;
    };
    /**
     * Cheerful Carnival team assignment (only present during cheerful_carnival events)
     */
    userCheerfulCarnival?: {
        [key: string]: unknown;
    };
    userProfileHonors?: Array<{
        [key: string]: unknown;
    }>;
    userHonorMissions?: Array<{
        [key: string]: unknown;
    }>;
    userPlayerFrames?: Array<{
        [key: string]: unknown;
    }>;
};

export type EventChapterTrackerRanking = {
    eventId?: number;
    gameCharacterId?: number;
    rankings?: Array<EventTrackerRanking>;
    userRankingStatus?: string;
};

/**
 * Requested server region
 */
export type Region = 'jp' | 'tw' | 'en' | 'kr';

export type GetEventChapterRankingsByEventIdAndCharaIdData = {
    body?: never;
    path: {
        /**
         * ID of the event
         */
        id: number;
    };
    query: {
        /**
         * Query rank of event rankings
         */
        rank?: number;
        /**
         * Query chapter of event rankings by charaId
         */
        charaId: number;
        /**
         * Query userId of event rankings
         */
        userId?: number;
        /**
         * Query limit of event rankings, if not set, default 1000
         */
        limit?: number;
        /**
         * Query page of event rankings
         */
        page?: number;
        /**
         * Query full data of event rankings
         */
        full?: boolean;
        /**
         * Query sort of event rankings
         */
        sort?: {
            [key: string]: unknown;
        };
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/{id}/chapter_rankings';
};

export type GetEventChapterRankingsByEventIdAndCharaIdResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
        data?: Array<EventTrackerRanking>;
    };
};

export type GetEventChapterRankingsByEventIdAndCharaIdResponse = GetEventChapterRankingsByEventIdAndCharaIdResponses[keyof GetEventChapterRankingsByEventIdAndCharaIdResponses];

export type PostEventChapterRankingData = {
    /**
     * event point record created by event score tracker
     */
    body: EventChapterTrackerData;
    path: {
        /**
         * ID of the event
         */
        id: number;
    };
    query?: {
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/{id}/chapter_rankings';
};

export type PostEventChapterRankingErrors = {
    /**
     * Unauthorized
     */
    401: FailureResponse;
};

export type PostEventChapterRankingError = PostEventChapterRankingErrors[keyof PostEventChapterRankingErrors];

export type PostEventChapterRankingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetEventChapterRankingGrpahByEventIdAndCharaIdData = {
    body?: never;
    path: {
        /**
         * ID of the event
         */
        id: number;
    };
    query: {
        /**
         * Query rank of event rankings
         */
        rank?: number;
        /**
         * Query chapter of event rankings by charaId
         */
        charaId: number;
        /**
         * Query userId of event rankings
         */
        userId?: number;
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/{id}/chapter_rankings/graph';
};

export type GetEventChapterRankingGrpahByEventIdAndCharaIdResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
        data?: {
            eventRankings?: Array<EventTrackerRanking>;
        };
    };
};

export type GetEventChapterRankingGrpahByEventIdAndCharaIdResponse = GetEventChapterRankingGrpahByEventIdAndCharaIdResponses[keyof GetEventChapterRankingGrpahByEventIdAndCharaIdResponses];

export type GetEventChapterRankingTimePointsData = {
    body?: never;
    path: {
        /**
         * ID of the event
         */
        id: number;
    };
    query: {
        /**
         * Query chapter of event rankings by charaId
         */
        charaId: number;
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/{id}/chapter_rankings/time';
};

export type GetEventChapterRankingTimePointsResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
        data?: Array<string>;
    };
};

export type GetEventChapterRankingTimePointsResponse = GetEventChapterRankingTimePointsResponses[keyof GetEventChapterRankingTimePointsResponses];

export type GetEventRankingLiveData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Query rank of event rankings
         */
        rank?: number;
        /**
         * Query userId of event rankings
         */
        userId?: number;
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/live';
};

export type GetEventRankingLiveResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
        data?: {
            eventRankings?: Array<EventTrackerRanking>;
        };
    };
};

export type GetEventRankingLiveResponse = GetEventRankingLiveResponses[keyof GetEventRankingLiveResponses];

export type GetEventChapterRankingLiveData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query rank of event rankings
         */
        rank?: number;
        /**
         * Query chapter of event rankings by charaId
         */
        charaId: number;
        /**
         * Query userId of event rankings
         */
        userId?: number;
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/live_chapter_rankings';
};

export type GetEventChapterRankingLiveResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
        data?: {
            eventRankings?: Array<EventTrackerRanking>;
        };
    };
};

export type GetEventChapterRankingLiveResponse = GetEventChapterRankingLiveResponses[keyof GetEventChapterRankingLiveResponses];

export type GetEventLatestChapterRankingLiveData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Query rank of event rankings
         */
        rank?: number;
        /**
         * Query userId of event rankings
         */
        userId?: number;
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/live_latest_chapter';
};

export type GetEventLatestChapterRankingLiveResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
        data?: {
            /**
             * ID of the game character
             */
            gameCharacterId?: number;
            eventRankings?: Array<EventTrackerRanking>;
        };
    };
};

export type GetEventLatestChapterRankingLiveResponse = GetEventLatestChapterRankingLiveResponses[keyof GetEventLatestChapterRankingLiveResponses];

export type GetEventRankingsByEventIdData = {
    body?: never;
    path: {
        /**
         * ID of the event
         */
        id: number;
    };
    query?: {
        /**
         * Query rank of event rankings
         */
        rank?: number;
        /**
         * Query userId of event rankings
         */
        userId?: number;
        /**
         * Query limit of event rankings, if not set, default 1000
         */
        limit?: number;
        /**
         * Query page of event rankings
         */
        page?: number;
        /**
         * Query full data of event rankings
         */
        full?: boolean;
        /**
         * Query sort of event rankings
         */
        sort?: {
            [key: string]: unknown;
        };
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/{id}/rankings';
};

export type GetEventRankingsByEventIdResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
        data?: Array<EventTrackerRanking>;
    };
};

export type GetEventRankingsByEventIdResponse = GetEventRankingsByEventIdResponses[keyof GetEventRankingsByEventIdResponses];

export type PostEventRankingData = {
    /**
     * event point record created by event score tracker
     */
    body: EventTrackerData;
    path: {
        /**
         * ID of the event
         */
        id: number;
    };
    query?: {
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/{id}/rankings';
};

export type PostEventRankingErrors = {
    /**
     * Unauthorized
     */
    401: FailureResponse;
};

export type PostEventRankingError = PostEventRankingErrors[keyof PostEventRankingErrors];

export type PostEventRankingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetEventRankingGrpahByEventIdData = {
    body?: never;
    path: {
        /**
         * ID of the event
         */
        id: number;
    };
    query: {
        /**
         * Query rank of event rankings
         */
        rank: number;
        /**
         * Query userId of event rankings
         */
        userId?: number;
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/{id}/rankings/graph';
};

export type GetEventRankingGrpahByEventIdResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
        data?: {
            eventRankings?: Array<EventTrackerRanking>;
        };
    };
};

export type GetEventRankingGrpahByEventIdResponse = GetEventRankingGrpahByEventIdResponses[keyof GetEventRankingGrpahByEventIdResponses];

export type GetEventRankingTimePointsData = {
    body?: never;
    path: {
        /**
         * ID of the event
         */
        id: number;
    };
    query?: {
        /**
         * Requested server region
         */
        region?: 'jp' | 'tw' | 'en' | 'kr';
    };
    url: '/event/{id}/rankings/time';
};

export type GetEventRankingTimePointsResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
        data?: Array<string>;
    };
};

export type GetEventRankingTimePointsResponse = GetEventRankingTimePointsResponses[keyof GetEventRankingTimePointsResponses];

export type GetApiInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetApiInfoResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetOpenApiSpecData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/spec';
};

export type GetOpenApiSpecResponses = {
    /**
     * Describe the generated OpenAPI specification
     */
    200: unknown;
};

export type HealthcheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type HealthcheckResponses = {
    /**
     * Healthy Service
     */
    200: unknown;
};
