apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-site
  namespace: account-site
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: account.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: account-site
                port:
                  number: 80
  tls:
    - hosts:
        - account.example.com
      secretName: account-site-tls
