import { addIcon } from "@iconify/svelte";
import menu from "@iconify-icons/mdi/menu";
import close from "@iconify-icons/mdi/close";
import homeVariantOutline from "@iconify-icons/mdi/home-variant-outline";
import paletteOutline from "@iconify-icons/mdi/palette-outline";
import cogOutline from "@iconify-icons/mdi/cog-outline";
import tuneVariant from "@iconify-icons/mdi/tune-variant";
import check from "@iconify-icons/mdi/check";
import brightnessAuto from "@iconify-icons/mdi/brightness-auto";
import whiteBalanceSunny from "@iconify-icons/mdi/white-balance-sunny";
import weatherNight from "@iconify-icons/mdi/weather-night";
import dramaMasks from "@iconify-icons/mdi/drama-masks";
import cubeOutline from "@iconify-icons/mdi/cube-outline";
import bookOpenVariant from "@iconify-icons/mdi/book-open-variant";
import arrowRight from "@iconify-icons/mdi/arrow-right";
import arrowLeft from "@iconify-icons/mdi/arrow-left";
import progressWrench from "@iconify-icons/mdi/progress-wrench";
import mapSearchOutline from "@iconify-icons/mdi/map-search-outline";
import refreshCircle from "@iconify-icons/mdi/refresh-circle";
import reload from "@iconify-icons/mdi/reload";
import pause from "@iconify-icons/mdi/pause";
import restart from "@iconify-icons/mdi/restart";
import translate from "@iconify-icons/mdi/translate";
import flaskOutline from "@iconify-icons/mdi/flask-outline";
import alertCircleOutline from "@iconify-icons/mdi/alert-circle-outline";
import scriptTextOutline from "@iconify-icons/mdi/script-text-outline";
import swapHorizontal from "@iconify-icons/mdi/swap-horizontal";
import playCircleOutline from "@iconify-icons/mdi/play-circle-outline";
import stopCircleOutline from "@iconify-icons/mdi/stop-circle-outline";
import volumeOff from "@iconify-icons/mdi/volume-off";
import imageOutline from "@iconify-icons/mdi/image-outline";
import musicNoteOutline from "@iconify-icons/mdi/music-note-outline";
import movieOpenOutline from "@iconify-icons/mdi/movie-open-outline";
import magnify from "@iconify-icons/mdi/magnify";
import alert from "@iconify-icons/mdi/alert";
import skipNext from "@iconify-icons/mdi/skip-next";
import accountGroupOutline from "@iconify-icons/mdi/account-group-outline";
import calendarStar from "@iconify-icons/mdi/calendar-star";
import accountVoice from "@iconify-icons/mdi/account-voice";
import cardMultipleOutline from "@iconify-icons/mdi/card-multiple-outline";
import mapMarkerRadiusOutline from "@iconify-icons/mdi/map-marker-radius-outline";
import autoFix from "@iconify-icons/mdi/auto-fix";
import skipPrevious from "@iconify-icons/mdi/skip-previous";
import downloadCircleOutline from "@iconify-icons/mdi/download-circle-outline";
import fullscreen from "@iconify-icons/mdi/fullscreen";
import fullscreenExit from "@iconify-icons/mdi/fullscreen-exit";
import phoneRotateLandscape from "@iconify-icons/mdi/phone-rotate-landscape";
import handHeart from "@iconify-icons/mdi/hand-heart";

addIcon("mdi:menu", menu);
addIcon("mdi:close", close);
addIcon("mdi:home-variant-outline", homeVariantOutline);
addIcon("mdi:palette-outline", paletteOutline);
addIcon("mdi:cog-outline", cogOutline);
addIcon("mdi:tune-variant", tuneVariant);
addIcon("mdi:check", check);
addIcon("mdi:brightness-auto", brightnessAuto);
addIcon("mdi:white-balance-sunny", whiteBalanceSunny);
addIcon("mdi:weather-night", weatherNight);
addIcon("mdi:drama-masks", dramaMasks);
addIcon("mdi:cube-outline", cubeOutline);
addIcon("mdi:book-open-variant", bookOpenVariant);
addIcon("mdi:arrow-right", arrowRight);
addIcon("mdi:arrow-left", arrowLeft);
addIcon("mdi:progress-wrench", progressWrench);
addIcon("mdi:map-search-outline", mapSearchOutline);
addIcon("mdi:refresh-circle", refreshCircle);
addIcon("mdi:reload", reload);
addIcon("mdi:pause", pause);
addIcon("mdi:restart", restart);
addIcon("mdi:translate", translate);
addIcon("mdi:flask-outline", flaskOutline);
addIcon("mdi:alert-circle-outline", alertCircleOutline);
addIcon("mdi:script-text-outline", scriptTextOutline);
addIcon("mdi:swap-horizontal", swapHorizontal);
addIcon("mdi:play-circle-outline", playCircleOutline);
addIcon("mdi:stop-circle-outline", stopCircleOutline);
addIcon("mdi:volume-off", volumeOff);
addIcon("mdi:image-outline", imageOutline);
addIcon("mdi:music-note-outline", musicNoteOutline);
addIcon("mdi:movie-open-outline", movieOpenOutline);
addIcon("mdi:magnify", magnify);
addIcon("mdi:alert", alert);
addIcon("mdi:skip-next", skipNext);
addIcon("mdi:account-group-outline", accountGroupOutline);
addIcon("mdi:calendar-star", calendarStar);
addIcon("mdi:account-voice", accountVoice);
addIcon("mdi:card-multiple-outline", cardMultipleOutline);
addIcon("mdi:map-marker-radius-outline", mapMarkerRadiusOutline);
addIcon("mdi:auto-fix", autoFix);
addIcon("mdi:skip-previous", skipPrevious);
addIcon("mdi:download-circle-outline", downloadCircleOutline);
addIcon("mdi:fullscreen", fullscreen);
addIcon("mdi:fullscreen-exit", fullscreenExit);
addIcon("mdi:phone-rotate-landscape", phoneRotateLandscape);
addIcon("mdi:hand-heart", handHeart);
