import { addIcon } from "@iconify/svelte";
import menu from "@iconify-icons/mdi/menu";
import close from "@iconify-icons/mdi/close";
import homeVariantOutline from "@iconify-icons/mdi/home-variant-outline";
import paletteOutline from "@iconify-icons/mdi/palette-outline";
import cogOutline from "@iconify-icons/mdi/cog-outline";
import tuneVariant from "@iconify-icons/mdi/tune-variant";
import check from "@iconify-icons/mdi/check";
import brightnessAuto from "@iconify-icons/mdi/brightness-auto";
import whiteBalanceSunny from "@iconify-icons/mdi/white-balance-sunny";
import weatherNight from "@iconify-icons/mdi/weather-night";
import dramaMasks from "@iconify-icons/mdi/drama-masks";
import cubeOutline from "@iconify-icons/mdi/cube-outline";
import bookOpenVariant from "@iconify-icons/mdi/book-open-variant";
import arrowRight from "@iconify-icons/mdi/arrow-right";
import arrowLeft from "@iconify-icons/mdi/arrow-left";
import progressWrench from "@iconify-icons/mdi/progress-wrench";
import mapSearchOutline from "@iconify-icons/mdi/map-search-outline";
import refreshCircle from "@iconify-icons/mdi/refresh-circle";
import reload from "@iconify-icons/mdi/reload";

addIcon("mdi:menu", menu);
addIcon("mdi:close", close);
addIcon("mdi:home-variant-outline", homeVariantOutline);
addIcon("mdi:palette-outline", paletteOutline);
addIcon("mdi:cog-outline", cogOutline);
addIcon("mdi:tune-variant", tuneVariant);
addIcon("mdi:check", check);
addIcon("mdi:brightness-auto", brightnessAuto);
addIcon("mdi:white-balance-sunny", whiteBalanceSunny);
addIcon("mdi:weather-night", weatherNight);
addIcon("mdi:drama-masks", dramaMasks);
addIcon("mdi:cube-outline", cubeOutline);
addIcon("mdi:book-open-variant", bookOpenVariant);
addIcon("mdi:arrow-right", arrowRight);
addIcon("mdi:arrow-left", arrowLeft);
addIcon("mdi:progress-wrench", progressWrench);
addIcon("mdi:map-search-outline", mapSearchOutline);
addIcon("mdi:refresh-circle", refreshCircle);
addIcon("mdi:reload", reload);
